# @package _global_
defaults:
  - override /optimizer: adamw_text_default
  - override /model: vanilla_1d_small
  - override /datamodule: conll2003

task:
  name: "ner_task"

trainer:
  accumulate_grad_batches: 1
