# @package _global_
defaults:
  - override /optimizer: adamw_cv_default
  - override /model: laplacian_pvt_small_cuda
  - override /datamodule: voc2012_segmentation

task:
  name: "semantic_segmentation"
  focal_gamma: 2.0
  focal_alpha: null
  focal_loss_weight: 1.0
  dice_loss_weight: 1.0
  dice_smooth: 0.00001

trainer:
  accumulate_grad_batches: 2
