name: "conll2003"
model_name: "bert-base-cased"
dataset_name: "eriktks/conll2003"
batch_size: 32
num_workers: 4
max_length: 128
num_classes: 9 # O, B-PER, I-PER, B-ORG, I-ORG, B-LOC, I-LOC, B-MISC, I-MISC
